-- Apollo enrichment fields
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS apollo_person_id TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS enrichment_status TEXT
  CHECK (enrichment_status IN ('pending_enrichment', 'enriching', 'enriched', 'enrichment_failed'));

-- Company description (generated by OpenAI during scoring)
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS company_description TEXT;
